language: node_js
node_js:
- node
- 6
deploy:
  on:
    tags: true
    branch: master
    node: 6
  provider: npm
  email: jakob.voss@gbv.de
  api_key:
    secure: Hgymcci5tJUN35MYxrmCJ6GYskoe9Gaz6Rh7sB6hdH1dVX532Zbq0v6OJMHhPy+ejpYWF3mKkNlwO79zd7dD+mPtY1A4toZCx8U4Wpbzf9OjBxEE+X7rwXj9JyuAVKY8XjTjiKxGY+sc/2L8Ti8gay2xLgygme3z6ITis8fUfCEth2xqViH97C7d9iD6xWcfLvRSzvoVCdp5rSgr+HMnVH9BqYnxOpXAGYrBAruhC0Xvv40BbHmE2auLiU4mnNvj82TMjv0okkzo6e/dk1n3J+J+I8NXVbRpFMOpTXgEp7SSMi7JWzOfUz2ttm1gNkCdQYie+ZrjQEAAzUGEkqNGjFHzhXo0KYIvTCNtB0tTIJ+tMbPiPcTzA/WaketlwrkgYS6Rx9l3y4RSoIEFJhcUIIrmseu6QokxmERyu08Q+YVVmvH36usTH2wsEa4/I8NFd0v4K3l1aSZOjQ4WZJFpOFAPdJOBvCegTLz8HkgW1f04daC22npIuzNB1zUoq/j/A/lKy/mXsW7mVfFPK8uny1wDeCfkJ5OanqVwOO8CE2Let70jangHgTH194egn98NXqea9RKk1Ni3Gl93/eVlufCaHpAxvAc2w59eTw6SfMtwgruzKhcXYjGozR2saNAqwZA4QyV1hA9SHdw9DuohQYrR0AjiOBKXHJ3QTdibQg0=
