language: node_js
node_js:
- node
- 6
deploy:
  on:
    tags: true
    branch: master
    node: 6
  provider: npm
  email: jakob.voss@gbv.de
  api_key:
    secure: fCnNQZPJbOUkCHjLoNfS0kfMufm+D6b3r0jQoJvFVaYMcBppf1qgtbk5ZFanC8RDJ3VUmOga600qW4mN+E689i+nrUdYDOB5pK3O82d/fX9JfRMedMldPXKVU2Vnys4n/RPP6sVZ/rv/aSUw0e7MFaUIz3OvrkietXYALXrxzAFEE/qTqYpCVmIY+s7qR1l4roVaQ5cUtpfU6HtVtxySFOXY6lacPJqCv2jp92Fkq1B0+Jerh/uD4nQr+N+wv/KwO6S7Eb6f0rytgtGLWI2sX26aiKQGsmqs62EOP4mrxL2cB24pI8cGoYn8s6RULyFrN1jtrtxGAOp4j+hwNwAF88HZrcsbj0W3o15LfGYrmq9wX0inSUYmgw2YFmIQBtTpeB7RIRML9ouZUYx3Fpns289896q1MySQnvN4XgLkN+p3S2xQXs0sxXFCM0nx7aGLM/dCGKxnAxTdMZ+wnNHfCLVEyAkds+/jOIVEpswkFg1ppmV8x+tTaQs+BB4oKMBdzswwQ+i6NDGfKwH3niW5zP4vWUxQGfjxeLrMExXmk/VXMNIozu6MfvT69jvqswS4W47FY+iG0pwVv1LmW3o+OrwtiaCDfZESwJ4y3PocpRlxopbyRNSp+8rbSyUyVvy99OOQuoHZagJmPk5rLkNECClcbBUXuIYqZmFTECL7wdc=
